import type { AlgorithmMetadata } from "../types";

export const ALGORITHM_METADATA: Record<string, AlgorithmMetadata> = {
  bubble: {
    id: "bubble",
    name: "Bubble Sort",
    description:
      "Repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order. The pass through the list is repeated until the list is sorted.",
    bestCase: "O(n)",
    averageCase: "O(n²)",
    worstCase: "O(n²)",
    spaceComplexity: "O(1)",
    stable: true,
    inPlace: true,
    pros: ["Simple to implement", "Stable", "In-place", "Adaptive for nearly sorted data"],
    cons: ["Poor performance on large lists", "Not practical for real-world use"],
    useCase: "Educational purposes, small datasets, nearly sorted data",
    pseudoCode: [
      "for i = 0 to n-1",
      "  for j = 0 to n-i-1",
      "    if arr[j] > arr[j+1]",
      "      swap(arr[j], arr[j+1])",
    ],
  },
  insertion: {
    id: "insertion",
    name: "Insertion Sort",
    description:
      "Builds the final sorted array one item at a time. It iterates through the array, and for each element, finds its correct position in the sorted portion and inserts it there.",
    bestCase: "O(n)",
    averageCase: "O(n²)",
    worstCase: "O(n²)",
    spaceComplexity: "O(1)",
    stable: true,
    inPlace: true,
    pros: ["Simple", "Efficient for small data", "Stable", "Online algorithm"],
    cons: ["O(n²) for random data", "Many comparisons for large arrays"],
    useCase: "Small datasets, nearly sorted data, online sorting",
    pseudoCode: [
      "for i = 1 to n-1",
      "  key = arr[i]",
      "  j = i - 1",
      "  while j >= 0 and arr[j] > key",
      "    arr[j+1] = arr[j]",
      "    j = j - 1",
      "  arr[j+1] = key",
    ],
  },
  selection: {
    id: "selection",
    name: "Selection Sort",
    description:
      "Divides the input into a sorted and unsorted region. It repeatedly selects the smallest element from the unsorted region and moves it to the sorted region.",
    bestCase: "O(n²)",
    averageCase: "O(n²)",
    worstCase: "O(n²)",
    spaceComplexity: "O(1)",
    stable: false,
    inPlace: true,
    pros: ["Simple", "Minimal swaps", "In-place"],
    cons: ["O(n²) always", "Not stable", "Not adaptive"],
    useCase: "When memory writes are expensive, small arrays",
    pseudoCode: [
      "for i = 0 to n-1",
      "  minIdx = i",
      "  for j = i+1 to n",
      "    if arr[j] < arr[minIdx]",
      "      minIdx = j",
      "  swap(arr[i], arr[minIdx])",
    ],
  },
  quick: {
    id: "quick",
    name: "Quick Sort",
    description:
      "Picks a pivot element and partitions the array so that smaller elements go left and larger go right. Recursively sorts the partitions.",
    bestCase: "O(n log n)",
    averageCase: "O(n log n)",
    worstCase: "O(n²)",
    spaceComplexity: "O(log n)",
    stable: false,
    inPlace: true,
    pros: ["Fast average case", "In-place", "Cache-friendly"],
    cons: ["Worst case O(n²)", "Not stable", "Pivot choice matters"],
    useCase: "General-purpose sorting, large datasets, when average performance matters",
    pseudoCode: [
      "function quickSort(arr, low, high)",
      "  if low < high",
      "    pivot = partition(arr, low, high)",
      "    quickSort(arr, low, pivot-1)",
      "    quickSort(arr, pivot+1, high)",
      "function partition(arr, low, high)",
      "  pivot = arr[high]",
      "  i = low - 1",
      "  for j = low to high-1",
      "    if arr[j] <= pivot",
      "      i++, swap(arr[i], arr[j])",
      "  swap(arr[i+1], arr[high])",
      "  return i+1",
    ],
  },
  merge: {
    id: "merge",
    name: "Merge Sort",
    description:
      "Divides the array into halves, recursively sorts them, then merges the two sorted halves. Uses a temporary array during merge.",
    bestCase: "O(n log n)",
    averageCase: "O(n log n)",
    worstCase: "O(n log n)",
    spaceComplexity: "O(n)",
    stable: true,
    inPlace: false,
    pros: ["Predictable O(n log n)", "Stable", "Good for linked lists"],
    cons: ["O(n) extra space", "Slower than quicksort in practice"],
    useCase: "When stability matters, external sorting, linked lists",
    pseudoCode: [
      "function mergeSort(arr, left, right)",
      "  if left < right",
      "    mid = (left + right) / 2",
      "    mergeSort(arr, left, mid)",
      "    mergeSort(arr, mid+1, right)",
      "    merge(arr, left, mid, right)",
      "function merge(arr, left, mid, right)",
      "  copy left and right halves to temp arrays",
      "  merge temp arrays back into arr",
    ],
  },
  heap: {
    id: "heap",
    name: "Heap Sort",
    description:
      "Builds a max-heap from the array, then repeatedly extracts the maximum and places it at the end. Uses the heap property for efficient extraction.",
    bestCase: "O(n log n)",
    averageCase: "O(n log n)",
    worstCase: "O(n log n)",
    spaceComplexity: "O(1)",
    stable: false,
    inPlace: true,
    pros: ["O(n log n) guaranteed", "In-place", "No worst-case degradation"],
    cons: ["Not stable", "Poor cache locality", "Slower than quicksort in practice"],
    useCase: "When guaranteed O(n log n) needed, memory-constrained systems",
    pseudoCode: [
      "function heapSort(arr)",
      "  buildMaxHeap(arr)",
      "  for i = n-1 down to 1",
      "    swap(arr[0], arr[i])",
      "    heapify(arr, 0, i)",
      "function heapify(arr, i, n)",
      "  largest = i",
      "  left = 2*i + 1, right = 2*i + 2",
      "  if left < n and arr[left] > arr[largest]",
      "    largest = left",
      "  if right < n and arr[right] > arr[largest]",
      "    largest = right",
      "  if largest != i",
      "    swap(arr[i], arr[largest])",
      "    heapify(arr, largest, n)",
    ],
  },
};
